version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./templates:/app/templates  # Add this line for template files
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  db:
    image: "sqlite:latest"
    volumes:
      - ./data:/data
