apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31041 
  type: NodePort


